import type { Lesson } from '@/shared/contracts';
export const LESSON_ID = 'nlhe-preflop-foundations-v1';
export const lesson: Lesson = {
  id: LESSON_ID, title: 'Position, Stacks und Preflop-Ranges', subtitle: 'Lies eine Hold’em-Range im richtigen Kontext, bevor du eine Aktion auswählst.', minutes: 8, category: 'No-Limit Texas Hold’em · Preflop',
  sections: [
    { title: 'Zwei Karten, sechs Positionen', body: 'No-Limit Texas Hold’em verwendet 52 Karten. Jede Person erhält zwei verdeckte Karten; bis zum River liegen fünf gemeinsame Karten. Du bildest die beste Fünf-Karten-Hand aus diesen sieben Karten. Vor dem Flop beginnt die Action im 6-max-Spiel bei UTG, gefolgt von HJ, CO, BTN, SB und BB. Auf späteren Straßen handelt die erste verbleibende Person links vom Button zuerst.\n\nPosition beschreibt, wann du Informationen über die Aktionen anderer erhältst. Der Button handelt nach dem Flop zuletzt, solange er in der Hand bleibt. Eine frühe Opening-Range und eine Button-Opening-Range haben deshalb unterschiedliche Aufgaben.' },
    { title: 'Der effektive Stack gehört zur Range', body: 'Der effektive Stack beschreibt in einem Zweispieler-Kontext den kleineren verfügbaren Anfangsstack. Hat der Button 100 BB und der Big Blind 75 BB, können sie gegeneinander höchstens 75 BB einsetzen. Mehrweg-Pots benötigen eigene Stack- und Side-Pot-Betrachtungen.\n\nKurze Stacks lassen weniger Raum für spätere Einsätze. Bei tiefen Stacks werden spätere Straßen und Position bedeutsamer. Unsere erste Lernbibliothek nimmt gleiche effektive Anfangsstacks, keine Antes und Rake 0 an. Ändere den Stack im Explorer und prüfe immer auch Open- und 3-Bet-Größe. Die angezeigten Heuristiken sind keine separat gelösten GTO-Datensätze.' },
    { title: '169 Klassen sind 1.326 Kombinationen', body: 'AA bezeichnet sechs konkrete Paar-Kombinationen. AKs enthält vier gleichfarbige Kombinationen; AKo enthält zwölf verschiedenfarbige. Die 13×13-Matrix ordnet Paare auf der Diagonale, suited Hände darüber und offsuit Hände darunter an. Zusammen sind das 169 Handklassen und 1.326 konkrete Starthände.\n\nBekannte Karten entfernen Kombinationen. Wenn du selbst ein Ass hältst, stehen deinem Gegner weniger Ass-Kombinationen zur Verfügung. Im Flop-Lernspot werden sowohl der Board als auch deine Hand aus der gegnerischen Range entfernt.' },
    { title: 'Die Vorgeschichte bestimmt die Entscheidung', body: 'RFI bedeutet Raise First In: Alle vor dir haben gefoldet. Gegen ein Open entscheidest du zwischen Fold, Call und 3-Bet. Nach deinem eigenen Open und einer gegnerischen 3-Bet sind Fold, Call und gegebenenfalls 4-Bet möglich. Gegen ein All-in gibt es bei gleichen effektiven Stacks keine weitere Erhöhung.\n\nEine Antwort auf eine 3-Bet kann nur Hände enthalten, mit denen du zuvor eröffnet hast. Deshalb zeigt der Explorer nicht erreichte Hände abgedunkelt. Die Trainingsauswahl berücksichtigt diese vorherige Range. Limps, zusätzliche Caller und Squeezes gehören nicht zum ersten Datensatz.' },
    { title: 'Mischungen und Datenherkunft richtig lesen', body: 'Eine Anzeige von 75 % Raise und 25 % Fold beschreibt eine Mischung über viele Gelegenheiten. Sie bedeutet nicht, dass eine einzelne Fold-Entscheidung automatisch falsch wäre. Beide Aktionen kommen in dieser Range vor. Der Trainer vergleicht deine Wahl mit diesem Plan; eine einzelne Hand prüft nicht, ob du langfristig in der vorgesehenen Häufigkeit mischst.\n\nAPPROXIMATED bedeutet hier: ursprüngliche Lernregeln mit groben 25-%-Mischungen, keine Solver-Berechnung und keine gemessene GTO-Genauigkeit. Ohne echte Aktions-EVs lässt sich kein EV-Verlust berechnen. Eine Range-Abweichung wird daher nicht als gemessener Geld- oder Chipverlust ausgegeben. Nutze diese erste Version, um Kontexte, Kombinationen und Range-Arbeit zu üben.' },
  ],
  takeaway: 'Wähle zuerst Stack, Position und Vorgeschichte. Lies danach die Handklasse und ihre Mischung — zusammen mit der Herkunft und den Grenzen der Range.',
  quiz: { question: 'Die Lernrange zeigt 75 % Raise und 25 % Fold. Was folgt daraus für einen einzelnen Fold?', options: ['Er ist immer falsch, weil Raise häufiger vorkommt.', 'Fold kommt in der Mischung vor. Ohne echte EV-Daten lässt sich daraus kein EV-Verlust bestimmen.', 'Ein Fold beweist, dass die gesamte Range GTO-optimal ist.'] },
};
export function isLessonAnswerCorrect(answer: number): boolean { return answer === 1; }
