"use client";

import Link from "next/link";
import { useState } from "react";
import { LESSON_PATH } from "@/shared/navigation";
import { lastSevenDays } from "@/shared/calendar";
import { ArrowRight, BookOpen, Check, ChevronRight, Clock3, Grid2X2, Target, TrendingUp } from "lucide-react";
import type { StudyDashboard } from "@/shared/contracts";
import { SessionGate } from "./auth-screen";
import { useResource, useSession } from "./study-context";
import { ActionLink, ErrorNotice, LoadingPanel, MiniDeck, PageHeader, number } from "./ui";

export function Dashboard() { return <SessionGate><DashboardContent /></SessionGate>; }
function DashboardContent() {
  const { user } = useSession();
  const [today] = useState(() => new Date().toISOString().slice(0, 10));
  const { data, loading, error, reload } = useResource<StudyDashboard>("/api/dashboard", !!user);
  if (loading) return <LoadingPanel />;
  if (error || !data) return <ErrorNotice message={error || "Dein Fortschritt ist noch nicht verfügbar."} retry={reload} />;
  const daily = lastSevenDays(data.daily, today);
  const hasPractice = daily.some(day => day.decisions > 0);
  const max = Math.max(4, ...daily.map((day) => day.decisions));
  const firstName = data.user.name.split(" ")[0];
  return <>
    <PageHeader title={`Dein Trainingsraum, ${firstName}.`} description="Eine gute Entscheidung beginnt mit einem klaren Gedanken." aside={<Link className="goal-chip" href="/settings"><Clock3 size={16} aria-hidden="true" />{number(data.user.weeklyGoal)} Lerntage pro Woche<ChevronRight size={14} aria-hidden="true" /></Link>} />
    <section className="metrics-rail" aria-label="Dein Lernfortschritt"><div className="metric"><span>Trainierte Entscheidungen<Target size={16} aria-hidden="true" /></span><strong>{number(data.decisions)}</strong><small>{data.decisions === 0 ? "Deine erste Entscheidung wartet" : "Im Kuhn-Trainer gespeichert"}</small></div><div className="metric"><span>Lernpunkte<TrendingUp size={16} aria-hidden="true" /></span><strong>{number(data.xp)}<em>XP</em></strong><small>Für Lektionen und Training</small></div><div className="metric"><span>Ø EV-Verlust<svg width="17" height="15" viewBox="0 0 17 15" fill="none" aria-hidden="true"><path d="m1 3 4 4 4-2 7 8M12 13h4V9" stroke="currentColor" strokeWidth="1.5" /></svg></span><strong>{data.averageRegret === null ? "—" : number(data.averageRegret, 3)}<em>{data.averageRegret === null ? "" : "Antes"}</em></strong><small>{data.averageRegret === null ? "Nach deinem ersten Training" : "Kuhn Poker · kleiner ist besser"}</small></div><div className="metric"><span>Lektionen abgeschlossen<BookOpen size={16} aria-hidden="true" /></span><strong>{data.lessonCompleted ? "1" : "0"}<em>/ 1</em></strong><small>Grundlagen der Entscheidung</small></div></section>
    <div className="dashboard-main"><section className="next-lesson panel"><div className="section-heading"><span className="subtle-label">Dein nächster Schritt</span><span className="lesson-tag">Grundlagen</span></div><div className="lesson-feature"><div className="lesson-feature-copy"><h2>{data.lessonCompleted ? "Jetzt wird Theorie zur Entscheidung." : "Denke in Entscheidungen. Nicht in Ergebnissen."}</h2><p>{data.lessonCompleted ? "Übe Check, Bet, Call und Fold in einem überschaubaren Spiel. Jede Entscheidung erhält berechnetes Feedback." : "Lerne, warum ein gutes Ergebnis nicht immer eine gute Entscheidung bedeutet — und was dir der Erwartungswert verrät."}</p><div className="lesson-meta"><span><Clock3 size={15} aria-hidden="true" />8 Minuten Lesezeit</span><span>Mit Wissensfrage</span></div><ActionLink href={data.lessonCompleted ? "/trainer" : LESSON_PATH}>{data.lessonCompleted ? "Training starten" : "Lektion beginnen"}</ActionLink></div><div className="lesson-art"><MiniDeck /><span>J / Q / K</span><small>Drei Karten. Ein klarer Lernfokus.</small></div></div><div className="learning-path"><span className="path-step current"><span>{data.lessonCompleted ? <Check size={13} aria-hidden="true" /> : "1"}</span>Verstehen</span><i /><span className={data.lessonCompleted ? "path-step current" : "path-step"}><span>2</span>Anwenden</span><i /><span className={data.decisions > 0 ? "path-step current" : "path-step"}><span>3</span>Verbessern</span></div></section>
    <section className="practice-panel panel"><div className="section-heading"><h2>Deine Praxis</h2><span className="subtle-label">Letzte 7 Tage</span></div><div className="practice-total"><strong>{number(daily.reduce((sum, day) => sum + day.decisions, 0))}</strong><span>Entscheidungen</span></div><div className="practice-chart" role="img" aria-label={hasPractice ? daily.map((day) => `${day.date}: ${day.decisions} Entscheidungen`).join("; ") : "Noch keine Trainingsentscheidungen"}>{hasPractice ? daily.map((day) => <div className="chart-column" key={day.date}><div className="chart-track"><span style={{ height: `${(day.decisions / max) * 100}%` }} /></div><small>{new Intl.DateTimeFormat("de-DE", { weekday: "short", timeZone: "UTC" }).format(new Date(`${day.date}T12:00:00Z`)).replace(".", "")}</small></div>) : <div className="chart-empty">Deine Aktivität erscheint nach dem ersten Training.</div>}</div><p className="practice-caption">Regelmäßig üben.<br /><strong>Bewusster entscheiden.</strong></p></section></div>
    <div className="dashboard-bottom"><section className="activity-section"><div className="section-heading"><h2>Zuletzt gelernt</h2><span className="subtle-label">Dein Lernverlauf</span></div>{data.recent.length ? <ul className="activity-list">{data.recent.slice(0, 4).map((entry) => <li key={entry.id}><span className="activity-icon"><Check size={16} aria-hidden="true" /></span><div><strong>{entry.label}</strong><span>{entry.detail}</span></div><time dateTime={entry.createdAt}>{new Intl.DateTimeFormat("de-DE", { day: "2-digit", month: "short" }).format(new Date(entry.createdAt))}</time></li>)}</ul> : <div className="empty-activity"><span className="activity-icon"><BookOpen size={20} aria-hidden="true" /></span><div><h3>Jeder Fortschritt fängt klein an.</h3><p>Schließe deine erste Lektion ab. Hier entsteht dein persönlicher Lernverlauf.</p></div></div>}</section><section className="explore-link-panel"><span className="explore-icon"><Grid2X2 size={21} aria-hidden="true" /></span><h2>Deine Range beginnt hier.</h2><p>169 Handklassen, 1.326 Kombinationen. Entdecke, wie sich Starthände zusammensetzen.</p><Link className="inline-link" href="/ranges">Range Explorer öffnen<ArrowRight size={16} aria-hidden="true" /></Link></section></div>
  </>;
}
