'use client';
import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { combosForClass, createCombo, getHandClass, type Card } from '@/domain/cards';
import { randomCards, randomFlop } from '@/domain/analysis';
import { BB, DEFAULT_STUDY, parseStudy, replayStudy, serializeStudy, studyUrl, type StudyConfig, type StudySpot } from '@/domain/study';
import { SIX_MAX_POSITIONS } from '@/domain/chips';
import { STACK_DEPTHS } from '@/shared/nlhe';
import type { StudyFrequency, StudyNode } from '@/strategy/study-provider';
import { SessionGate } from './auth-screen';
import { api, useResource } from './study-context';
import { ErrorNotice, number, PageHeader } from './ui';
import { HoldemCards } from './nlhe-ui';
import { cardLabel, CardPicker, StudyMatrix } from './study-widgets';
import { StudyAnalysis } from './study-analysis';

const DEFAULT_SPOT:StudySpot={schema:2,config:DEFAULT_STUDY,heroHand:['As','Ks'],events:[{kind:'deal',cards:['Kh','8s','4c']}]};
function useStudyNode(key:string){const [result,setResult]=useState<{key:string;node?:StudyNode;error?:string}|null>(null);useEffect(()=>{const abort=new AbortController();api<StudyNode>('/api/study/node',{method:'POST',body:key,signal:abort.signal}).then(node=>setResult({key,node})).catch((e:unknown)=>{if(!abort.signal.aborted)setResult({key,error:e instanceof Error?e.message:'Node konnte nicht geladen werden.'});});return()=>abort.abort();},[key]);return result?.key===key?result:null;}
export function Postflop(){return <SessionGate><StudyExplorer/></SessionGate>;}
function StudyExplorer(){
  const search=useSearchParams();let initialError='';let spot=DEFAULT_SPOT;
  try{if(search.get('spot'))spot=parseStudy(search.get('spot')!);}catch(e){initialError=e instanceof Error?e.message:'Ungültiger Spot-Link.';}
  const key=serializeStudy(spot),state=replayStudy(spot),resource=useStudyNode(key),node=resource?.node;
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[slot,setSlot]=useState<string|null>(null),[selected,setSelected]=useState('AKs');
  const [branches,setBranches]=useState<StudySpot[]>([]),[filter,setFilter]=useState('random'),[busy,setBusy]=useState(false);
  const [training,setTraining]=useState(false),[feedback,setFeedback]=useState<{key:string;actions:StudyFrequency[];chosenAction:string;chosenFrequency:number;evLoss:number|null}|null>(null),[attempt,setAttempt]=useState<string|null>(null);
  const saved=useResource<{id:string;spot:StudySpot;label:string;favorite:boolean}[]>('/api/study/saved');
  const progress=useResource<{total:{decisions:number}[];recent:{id:string;spot:StudySpot;chosen_action:string}[]}>('/api/study/progress');
  const activeCombo=node?.hero.find(c=>c.cards.join('')===createCombo(...spot.heroHand).join(''));
  const visitedNode=node?.id;
  useEffect(()=>{if(!visitedNode)return;const timer=setTimeout(()=>{void api('/api/study/saved',{method:'POST',body:JSON.stringify({spot:JSON.parse(key),favorite:false})}).catch(()=>{/* A failed history save must not interrupt study; explicit saving offers errors/retry. */});},1200);return()=>clearTimeout(timer);},[visitedNode,key]);
  function navigate(next:StudySpot,keepBranch=true){try{replayStudy(next);if(keepBranch)setBranches(previous=>[spot,...previous.filter(s=>serializeStudy(s)!==key)].slice(0,20));window.history.replaceState(null,'',studyUrl(next));setError('');setNotice('');setAttempt(null);}catch(e){setError(e instanceof Error?e.message:'Ungültige Action.');}}
  function configure(change:Partial<StudyConfig>){navigate({...spot,config:{...spot.config,...change},events:spot.events.filter(e=>e.kind==='deal').slice(0,1)});}
  async function save(favorite:boolean){try{await api('/api/study/saved',{method:'POST',body:JSON.stringify({spot,favorite})});saved.reload();setNotice(favorite?'Favorit gespeichert.':'Spot im Verlauf gespeichert.');}catch(e){setError((e as Error).message);}}
  async function act(actionId:string){if(!node)return;const selectedAction=node.legalActions.find(a=>a.id===actionId)!;
    if(training&&state.activePlayer===spot.config.hero){setBusy(true);const id=attempt??crypto.randomUUID();setAttempt(id);try{const answer=await api<NonNullable<typeof feedback>>('/api/study/decision',{method:'POST',body:JSON.stringify({spot,actionId,attemptId:id})});setFeedback({...answer,key});progress.reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}return;}
    navigate({...spot,events:[...spot.events,{kind:'action',actor:state.activePlayer!,action:selectedAction.action}]});
  }
  function pick(card:Card){try{if(slot?.startsWith('hero')){const cards=[...spot.heroHand] as [Card,Card];cards[Number(slot.at(-1))]=card;navigate({...spot,heroHand:createCombo(...cards)});setSelected(getHandClass(cards));}
    else if(slot?.startsWith('flop')){const flop=(spot.events.find(e=>e.kind==='deal') as {cards:Card[]}|undefined)?.cards??[];const cards=[...flop];cards[Number(slot.at(-1))]=card;navigate({...spot,events:[{kind:'deal',cards}]});}
    else if(slot==='next')navigate({...spot,events:[...spot.events,{kind:'deal',cards:[card]}]});setSlot(null);
  }catch(e){setError((e as Error).message);}}
  const blocked=[...spot.heroHand,...state.board].filter(card=>slot?.startsWith('hero')?card!==spot.heroHand[Number(slot.at(-1))]:slot?.startsWith('flop')?card!==state.board[Number(slot.at(-1))]:true);
  const currentFeedback=feedback?.key===key?feedback:null;
  return <><PageHeader title="NLHE Study Engine" description="6-max ChipEV · Heads-Up Postflop · Rake 0"/><div className="engine-toolbar"><button className="button button-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}${studyUrl(spot)}`);setNotice('Spot-Link kopiert.');}catch{setNotice('Der reproduzierbare Link steht in der Adresszeile.');}}}>Spot teilen</button><button className="button button-secondary" onClick={()=>save(true)}>Als Favorit speichern</button><button className="button button-secondary" onClick={()=>save(false)}>Im Verlauf speichern</button><button className="button button-secondary" onClick={()=>{setTraining(!training);setFeedback(null);}}>{training?'Zurück zum Explorer':'Diesen Spot trainieren'}</button></div>
    {error||initialError||resource?.error?<ErrorNotice message={error||initialError||resource?.error||''}/>:null}{notice?<p role="status">{notice}</p>:null}
    <div className="engine-layout"><aside className="engine-config panel"><h2>Spot konfigurieren</h2><label>Format<select aria-label="Format"><option>6-max NLHE ChipEV</option></select></label><label>Stack<select aria-label="Study Stack" value={spot.config.stackBb} onChange={e=>configure({stackBb:Number(e.target.value),threeBetBb:Math.min(Number(e.target.value),spot.config.threeBetBb),fourBetBb:Math.min(Number(e.target.value),spot.config.fourBetBb)})}>{[...new Set([...STACK_DEPTHS,spot.config.stackBb])].map(s=><option key={s} value={s}>{s} BB</option>)}</select></label><label>Custom Stack<input type="number" min="10" max="500" step="0.01" defaultValue={spot.config.stackBb} onBlur={e=>{if(Number(e.target.value)!==spot.config.stackBb)configure({stackBb:Number(e.target.value)});}}/></label>
    <label>Hero<select aria-label="Hero Position" value={spot.config.hero} onChange={e=>{const hero=e.target.value as StudyConfig['hero'];const villain=hero==='BB'?'BTN':'BB';configure({hero,villain,opener:hero==='BB'?'BTN':hero});}}>{SIX_MAX_POSITIONS.map(p=><option key={p}>{p}</option>)}</select></label><label>Villain<select aria-label="Villain Position" value={spot.config.villain} onChange={e=>{const villain=e.target.value as StudyConfig['villain'];configure({villain,opener:SIX_MAX_POSITIONS.indexOf(spot.config.hero)<SIX_MAX_POSITIONS.indexOf(villain)?spot.config.hero:villain});}}>{SIX_MAX_POSITIONS.filter(p=>p!==spot.config.hero).map(p=><option key={p}>{p}</option>)}</select></label>
    <label>Preflop Line<select aria-label="Preflop Line" value={spot.config.line} onChange={e=>configure({line:e.target.value as StudyConfig['line']})}><option value="srp">Open / Call · SRP</option><option value="3bet">Open / 3-Bet / Call</option><option value="4bet">Open / 3-Bet / 4-Bet / Call</option></select></label>{(['openBb','threeBetBb','fourBetBb'] as const).map((field,i)=><label key={field}>{['Open Size','3-Bet Size','4-Bet Size'][i]}<input aria-label={`Study ${['Open Size','3-Bet Size','4-Bet Size'][i]}`} type="number" min="2" max={spot.config.stackBb} step="0.05" key={`${field}-${spot.config[field]}`} defaultValue={spot.config[field]} onBlur={e=>{if(Number(e.target.value)!==spot.config[field])configure({[field]:Number(e.target.value)});}}/></label>)}<p>{spot.config.opener} eröffnet. Nicht beteiligte Blinds bleiben im Pot. Änderungen beginnen einen neuen Branch.</p></aside>
    <section className="engine-center"><div className="engine-table panel"><div className="engine-ledger"><strong data-testid="study-pot">Pot {number(state.pot/BB,3)} BB</strong><span>SPR {number(Math.min(...state.players.map(p=>p.stack))/Math.max(1,state.pot),2)}</span>{state.players.map(p=><span key={p.position}>{p.position}: {number(p.stack/BB,3)} BB</span>)}</div><h2>{state.street==='preflop'?'Flop wählen':state.street}</h2><div className="engine-board">{state.board.slice(0,3).map((card,i)=><button key={i} aria-label={`Flopkarte ${i+1}: ${cardLabel(card)}`} onClick={()=>setSlot(`flop${i}`)}><HoldemCards cards={[card]}/></button>)}{state.board.slice(3).map((card,i)=><div key={i}><HoldemCards cards={[card]}/><button className="text-button" onClick={()=>{let deals=0;const index=spot.events.findIndex(e=>e.kind==='deal'&&++deals===i+2);navigate({...spot,events:spot.events.slice(0,index)});}}>{i===0?'Turn':'River'} zurücksetzen</button></div>)}</div><div className="engine-hand">{spot.heroHand.map((card,i)=><button key={i} aria-label={`Herokarte ${i+1}: ${cardLabel(card)}`} onClick={()=>setSlot(`hero${i}`)}><HoldemCards cards={[card]}/></button>)}<span>{spot.config.hero} · {getHandClass(spot.heroHand)}</span></div>
    <div className="engine-toolbar"><button className="text-button" onClick={()=>{const hand=createCombo(...randomCards(2,state.board) as [Card,Card]);navigate({...spot,heroHand:hand});setSelected(getHandClass(hand));}}>Zufällige Hero-Hand</button><button className="text-button" onClick={()=>navigate({...spot,events:[{kind:'deal',cards:randomFlop(filter,spot.heroHand)}]})}>Zufallsflop</button><button className="text-button" onClick={()=>navigate({...spot,events:[]})}>Flop zurücksetzen</button></div><label>Boardfilter<select aria-label="Boardfilter" value={filter} onChange={e=>setFilter(e.target.value)}>{['random','ace-high','king-high','paired','monotone','two-tone','connected','low'].map(f=><option key={f}>{f}</option>)}</select></label>
    {slot?<CardPicker blocked={blocked} onPick={pick} onClose={()=>setSlot(null)}/>:null}
    {state.awaitingBoard?<button className="button button-primary" onClick={()=>state.street==='preflop'?navigate({...spot,events:[{kind:'deal',cards:randomFlop(filter,spot.heroHand)}]}):setSlot('next')}>{state.street==='preflop'?'Flop geben':state.street==='flop'?'Turnkarte wählen':'Riverkarte wählen'}</button>:null}
    <h3>{state.complete?'Hand abgeschlossen':state.activePlayer?`${state.activePlayer} ist am Zug`:'Setzrunde abgeschlossen'}</h3>{!resource?<p role="status">Node wird geladen…</p>:null}<div className="engine-actions">{node?.legalActions.map(a=><button key={a.id} className="button button-secondary" disabled={busy||!!(training&&currentFeedback)} onClick={()=>act(a.id)}>{a.label}</button>)}</div>
    {training?<div className="engine-feedback"><h3>Spot-Trainer</h3><a className="button button-secondary" href={`/trainer?study=${encodeURIComponent(serializeStudy(spot))}`}>Trainingssitzung konfigurieren</a><p>Gespeicherte Study-Entscheidungen: {progress.data?.total[0]?.decisions??0}. Lernstrategie, keine GTO-Accuracy.</p>{state.activePlayer!==spot.config.hero?<p>Spiele die Villain-Action, bis Hero am Zug ist.</p>:!activeCombo?.reach?<p>Diese Hand erreicht die Lernrange nicht. Wähle eine Hand mit Reach &gt; 0.</p>:null}{currentFeedback?<><p>Gespeichert: {currentFeedback.chosenAction} · Lernfrequenz {number(currentFeedback.chosenFrequency*100)} %</p><button className="button button-primary" onClick={()=>{const a=node!.legalActions.find(a=>a.id===currentFeedback.chosenAction)!;navigate({...spot,events:[...spot.events,{kind:'action',actor:state.activePlayer!,action:a.action}]});}}>Mit dieser Action fortfahren</button><button className="text-button" onClick={()=>{setTraining(false);setNotice('Training abgeschlossen. Deine Entscheidung bleibt gespeichert.');}}>Training abschließen</button></>:null}</div>:null}</div>
    <section className="engine-history panel"><h2>Action Tree</h2><div><button onClick={()=>navigate({...spot,events:[]})}>Preflop</button>{spot.events.map((event,i)=><button key={i} aria-current={i===spot.events.length-1?'step':undefined} onClick={()=>navigate({...spot,events:spot.events.slice(0,i+1)})}>{event.kind==='deal'?event.cards.map(cardLabel).join(' '):`${event.actor} ${event.action.type}${'toBb' in event.action?` ${event.action.toBb} BB`:''}`}</button>)}</div><details><summary>Vollständige Action History</summary><ol>{state.actionHistory.map((a,i)=><li key={i}>{a.street} · {a.actor} {a.action} · {number(a.paidBb,3)} BB gezahlt</li>)}</ol></details>{branches.length?<details><summary>Frühere Branches ({branches.length})</summary>{branches.map((branch,i)=><button className="text-button" key={i} onClick={()=>navigate(branch,false)}>{replayStudy(branch).street} · {branch.events.length} Schritte · {branch.heroHand.map(cardLabel).join(' ')}</button>)}</details>:null}</section></section>
    <StudyAnalysis spot={spot} node={node} selected={selected} hidden={training&&!currentFeedback} onChoose={hand=>navigate({...spot,heroHand:hand})}/></div>
    {node?<div className="engine-ranges"><StudyMatrix rows={node.heroClasses} selected={selected} label="Hero Range" onSelect={hand=>{setSelected(hand);const combo=combosForClass(hand,state.board)[0];if(combo)navigate({...spot,heroHand:combo});}}/><StudyMatrix rows={node.villainClasses} selected={selected} label="Villain Range" onSelect={setSelected}/></div>:null}
    <section className="engine-library panel"><h2>Favoriten & Verlauf</h2>{saved.data?.length?saved.data.map(row=><div key={row.id}><button className="text-button" onClick={()=>navigate(row.spot)}>{row.favorite?'★ ':''}{row.label}</button><button className="text-button" aria-label={`Entfernen: ${row.label}`} onClick={async()=>{try{await api('/api/study/saved',{method:'DELETE',body:JSON.stringify({id:row.id})});saved.reload();}catch(e){setError((e as Error).message);}}}>Entfernen</button></div>):<p>Speichere einen Spot, um ihn nach erneuter Anmeldung wieder zu öffnen.</p>}{progress.data?.recent.length?<details><summary>Zuletzt trainierte Entscheidungen</summary>{progress.data.recent.map(item=><button className="text-button" key={item.id} onClick={()=>navigate(item.spot)}>{item.spot.heroHand.join(' ')} · {item.chosen_action}</button>)}</details>:null}</section>
  </>;
}
