'use client';
import { useState } from 'react';
import { combosForClass, createCombo, getHandClass, type Combo } from '@/domain/cards';
import { handFeatures } from '@/domain/analysis';
import { replayStudy, serializeStudy, type StudySpot } from '@/domain/study';
import type { EquityResult } from '@/domain/equity';
import type { StudyNode } from '@/strategy/study-provider';
import { api } from './study-context';
import { number } from './ui';
import { HoldemCards } from './nlhe-ui';
import type { rangeDensities } from '@/domain/range-analysis';
function RangeAnalysis({spot}:{spot:StudySpot}){
  const [result,setResult]=useState<{key:string;data:ReturnType<typeof rangeDensities>}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const key=serializeStudy(spot);
  return <section><button className="button button-secondary" disabled={busy} onClick={async()=>{setBusy(true);try{setResult({key,data:await api('/api/study/analysis',{method:'POST',body:key})});setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Range-Dichten berechnen</button>{error?<p role="alert">{error}</p>:null}{result?.key===key?<><table><caption>Gewichtete Dichten der aktuellen Ranges</caption><thead><tr><th>Merkmal</th><th>Hero</th><th>Villain</th></tr></thead><tbody>{(['topPair','overpair','set','strongDraw','air','currentNuts'] as const).map(metric=><tr key={metric}><th>{({topPair:'Top Pair',overpair:'Overpair',set:'Set',strongDraw:'Direkter Draw',air:'Air',currentNuts:'Aktuelle Nuts'})[metric]}</th><td>{number(result.data.hero[metric]*100,1)} %</td><td>{number(result.data.villain[metric]*100,1)} %</td></tr>)}</tbody></table><p>Nut Advantage (Hero minus Villain): {number(result.data.nutAdvantage*100,1)} Prozentpunkte. Nuts = aktuell bestmögliche gemachte Hand auf diesem Board. Keine zukünftige Nuts-Equity. Merkmale können sich überschneiden.</p></>:null}</section>;
}
export function StudyAnalysis({spot,node,selected,hidden,onChoose}:{spot:StudySpot;node:StudyNode|undefined;selected:string;hidden:boolean;onChoose:(cards:Combo)=>void}){
  const [tab,setTab]=useState('Strategy'),[mode,setMode]=useState('hand-range'),[villainHand,setVillainHand]=useState('QhQd'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{key:string;value:EquityResult}|null>(null);
  const state=node?.state??replayStudy(spot),key=serializeStudy(spot)+mode+villainHand;
  const attributes=state.board.length>=3?handFeatures(spot.heroHand,state.board):null;
  const active=node?.hero.find(c=>c.cards.join('')===createCombo(...spot.heroHand).join(''));
  const policy=state.activePlayer===spot.config.hero?active:node?.villainClasses.find(c=>c.handClass===selected);
  async function calculate(){setBusy(true);setError('');try{const value=await api<EquityResult>('/api/study/equity',{method:'POST',body:JSON.stringify({spot,mode,...(mode==='hand-hand'?{villainHand:[villainHand.slice(0,2),villainHand.slice(2,4)]}:{})})});setResult({key,value});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <aside className="engine-analysis panel"><div className="engine-tabs" role="tablist" aria-label="Study Analyse">{['Strategy','Range','Combos','Equity','Analysis','Why?'].map(name=><button role="tab" aria-selected={tab===name} key={name} onClick={()=>setTab(name)}>{name}</button>)}</div><section role="tabpanel" aria-label={tab}>
    {tab==='Strategy'?<><h2>{hidden?'Erst entscheiden':node?.provenance.sourceType==='APPROXIMATED'?'Approximate Training Strategy':'Strategy'}</h2><p>{node?.provenance.sourceType === "APPROXIMATED" ? "Keine echte Solver-Solution. " : ""}{policy?.actions.some(a=>a.ev!==null) ? "Action-EVs aus der angegebenen Solution." : "EV data unavailable."}</p>{node?.unavailable?<p>{node.unavailable}</p>:hidden?<p>Der Strategievergleich erscheint nach deiner Antwort.</p>:<>{(policy?.reach ? policy.actions : [])?.map(a=><p className="engine-frequency" key={a.action}><span>{node?.legalActions.find(x=>x.id===a.action)?.label??a.action}</span><strong>{number(a.frequency*100)} %{a.ev!==null ? ` · EV ${number(a.ev,3)} BB` : ""}</strong></p>)}<p>{policy?.reach ? "" : "Die ausgewählte Hand erreicht die aktive Range nicht. "}Aktueller Reach von {getHandClass(spot.heroHand)}: {number((active?.reach??0)*100,1)} %</p></>}</>:null}
    {tab==='Combos'?<><h2>Konkrete Combos · {selected}</h2><div className="engine-combos">{combosForClass(selected,state.board).map(combo=><button key={combo.join('')} onClick={()=>onChoose(combo)}><HoldemCards cards={combo} small/></button>)}</div><p>Die Auswahl aktualisiert die Hero-Hand und gegnerische Blocker.</p></>:null}
    {tab==='Range'?<><h2>Range Funnel</h2>{node?.funnel.map((f,i)=><div className="engine-funnel" key={i}><span>{f.label}</span><p>Hero {number(f.hero,2)} · Villain {number(f.villain,2)} gewichtete Combos</p></div>)}<p>Reach × Lernfrequenz pro gewählter Action. Boardkarten werden entfernt. Die Villain-Matrix entfernt zusätzlich deine konkrete Hand.</p></>:null}
    {tab==='Equity'?<><h2>Showdown-Equity</h2><label>Vergleich<select aria-label="Vergleich" value={mode} onChange={e=>setMode(e.target.value)}><option value="hand-range">Hand vs Range</option><option value="range-range">Range vs Range</option><option value="hand-hand">Hand vs Hand</option></select></label>{mode==='hand-hand'?<label>Villain-Hand, z. B. QhQd<input value={villainHand} onChange={e=>setVillainHand(e.target.value)} maxLength={4}/></label>:null}<button className="button button-secondary" disabled={busy||state.board.length<3} onClick={calculate}>{busy?'Equity wird berechnet…':'Equity berechnen'}</button>{error?<p role="alert">{error}</p>:null}{result?.key===key?<><p>Hero {number(result.value.hero*100,1)} % · Villain {number(result.value.villain*100,1)} %</p><p>{result.value.method==='exact'?'Exakte Enumeration':'Monte-Carlo-Schätzung'} · {result.value.samples} Runouts · Standardfehler {number(result.value.standardError*100,2)} Prozentpunkte.</p></>:null}<p>Keine zukünftigen Folds oder Bet-EVs. Range vs Range verwendet unbekannte Hole Cards beider Spieler.</p></>:null}
    {tab==='Analysis'?<><h2>Board & Hand</h2><p>{attributes?.texture.join(' · ')}</p><p>{attributes?.category}</p>{attributes?<ul>{Object.entries(attributes).filter(([,v])=>v===true).map(([name])=><li key={name}>{name}</li>)}</ul>:null}<p>{attributes?.blockers.join(' ')}</p><RangeAnalysis spot={spot}/></>:null}
    {tab==='Why?'?<><h2>Warum könnte das relevant sein?</h2><p>Eine mögliche strategische Begründung ergibt sich aus diesen Merkmalen; keine Erklärung einer Solver-Entscheidung.</p>{attributes?<ul><li>Deine aktuelle Handkategorie ist {attributes.category}. Sie allein bestimmt keine optimale Action.</li>{attributes.flushDraw?<li>Vier Karten einer Farbe geben einen direkten Flush Draw.</li>:null}{attributes.backdoorFlush?<li>Drei Karten einer Farbe auf dem Flop ermöglichen einen Backdoor Flush.</li>:null}{attributes.straightDraw?<li>Ein Straight Draw kann sich mit folgenden Rängen verbessern: {attributes.straightOutRanks.join(', ')}.</li>:null}{attributes.backdoorStraight?<li>Eine Straight ist über zwei passende spätere Karten möglich.</li>:null}<li>SPR {number(Math.min(...state.players.map(p=>p.stack))/Math.max(state.pot,1),2)} beschreibt den verbleibenden Stack relativ zum Pot.</li><li>Deine Karten entfernen gegnerische Combos. Daraus folgt kein Nachweis für profitablen Bluff oder Fold Equity.</li></ul>:null}</>:null}</section>
    {node?<details className="engine-source"><summary>Solution Info · {node.provenance.sourceType}</summary><p>{node.provenance.description}</p><p>Version: {node.provenance.solutionVersion}</p><p>Solver: {node.provenance.solverVersion??'Unavailable'} · EV accuracy: {node.provenance.accuracy.value??'Unavailable'}</p><ul>{node.provenance.assumptions.map(a=><li key={a}>{a}</li>)}</ul></details>:null}</aside>;
}
