'use client';
import { useRef,useState } from 'react';
import { useRouter,useSearchParams } from 'next/navigation';
import { BB,parseStudy,replayStudy,serializeStudy,studyUrl,type StudySpot } from '@/domain/study';
import type { getStudyTraining } from '@/server/study-training';
import { api,useResource } from './study-context';
import { ActionLink,ErrorNotice,LoadingPanel,number,PageHeader } from './ui';
import { HoldemCards } from './nlhe-ui';
type Session=Awaited<ReturnType<typeof getStudyTraining>>;
export function StudyTrainer(){
  const search=useSearchParams(),router=useRouter(),id=search.get('studySession');let root:StudySpot|null=null,invalid='';try{if(search.get('study'))root=parseStudy(search.get('study')!);}catch(e){invalid=(e as Error).message;}
  const stored=useResource<Session>(`/api/study/training?id=${id}`,!!id),[updated,setUpdated]=useState<Session|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [mode,setMode]=useState('spot'),[boardFilter,setFilter]=useState('fixed'),[limit,setLimit]=useState(10),client=useRef<{key:string;id:string}|null>(null);
  const session=updated?.id===id?updated:stored.data;
  async function command(command:'start'|'answer'|'next'|'finish',actionId?:string){setBusy(true);setError('');try{
    const key=root?serializeStudy(root)+JSON.stringify({mode,boardFilter,limit}):'';if(command==='start'&&client.current?.key!==key)client.current={key,id:crypto.randomUUID()};
    const input=command==='start'?{command,spot:root,options:{mode,boardFilter,limit},clientId:client.current!.id}:command==='answer'?{command,id,questionId:session!.question!.id,actionId}:{command,id};
    const value=await api<Session>('/api/study/training',{method:'POST',body:JSON.stringify(input)});setUpdated(value);if(command==='start'){client.current=null;router.replace(`/trainer?studySession=${value.id}`);}
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(invalid)return <ErrorNotice message={invalid}/>;
  if(!id)return <><PageHeader title="Postflop-Trainer" description="Exakte Study-Nodes · gespeicherte Antworten · keine GTO-Behauptung"/>{root?<section className="panel course-entry"><h2>{root.config.stackBb} BB · {root.config.hero} vs {root.config.villain}</h2><p>Der Trainer nutzt dieselbe Range, Action-Historie und Datenquelle wie der Explorer. Jede Frage wird mit ihrer Strategieversion eingefroren.</p><div className="nlhe-controls"><label>Trainingsmodus<select aria-label="Trainingsmodus" value={mode} onChange={e=>setMode(e.target.value)}><option value="spot">Spot Trainer</option><option value="street">Street Trainer</option><option value="full-hand">Full Hand Trainer</option></select></label><label>Boards<select aria-label="Trainingsboards" value={boardFilter} onChange={e=>setFilter(e.target.value)}>{['fixed','random','ace-high','king-high','paired','monotone','two-tone','connected','low'].map(f=><option key={f}>{f}</option>)}</select></label><label>Entscheidungen<select aria-label="Trainingslänge" value={limit} onChange={e=>setLimit(Number(e.target.value))}>{[10,25,50,100].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div><p>{mode==='full-hand'?'Spiele ab diesem Node weiter bis zum River. Villain-Aktionen werden aus der Lernstrategie gezogen; nach Handende beginnt eine neue Hand.':'Trainiere wiederholt die gewählte Street und Action-Historie mit neuen unblocked Hero-Combos.'}</p><p>Ohne EV-Daten bedeutet Feedback nur Übereinstimmung mit der gekennzeichneten Lernstrategie.</p><button className="button button-primary" disabled={busy} onClick={()=>command('start')}>Study-Training starten</button><ActionLink href={studyUrl(root)} secondary>Zum gewählten Spot</ActionLink>{error?<ErrorNotice message={error}/>:null}</section>:<ErrorNotice message="Wähle zuerst einen Hero-Node im Postflop Explorer."/>}</>;
  if(!session)return stored.error?<ErrorNotice message={stored.error} retry={stored.reload}/>:<LoadingPanel/>;
  if(session.complete)return <><PageHeader title="Study-Training abgeschlossen" description={`${session.answered} Entscheidungen gespeichert.`}/><ActionLink href="/postflop">Study Engine öffnen</ActionLink><ActionLink href="/" secondary>Fortschritt ansehen</ActionLink></>;
  const question=session.question;if(!question)return <ErrorNotice message="Die erste Frage konnte nicht erzeugt werden. Starte das Training erneut."/>;
  const state=replayStudy(question.spot),feedback=question.feedback;
  const actions=feedback?.actions as {action:string;frequency:number;ev:number|null}[]|undefined;
  return <><PageHeader title="NLHE Study-Trainer" description={`${session.options.mode} · ${question.spot.config.stackBb} BB · ${state.street}`} aside={<span>Entscheidung {question.ordinal} / {session.options.limit}</span>}/><p className="nlhe-provenance">{question.provenance.sourceType} · Approximate Training Strategy · EV data unavailable</p><div className="nlhe-training-layout"><section className="nlhe-table panel"><h2>{question.spot.config.hero} ist am Zug</h2><p>Pot {number(state.pot/BB,3)} BB · {question.spot.config.hero} {number(state.players.find(p=>p.position===question.spot.config.hero)!.stack/BB,3)} BB</p><HoldemCards cards={state.board}/><HoldemCards cards={question.spot.heroHand}/><div className="nlhe-action-buttons">{question.actions.map(a=><button className="button button-secondary" key={a.id} disabled={busy||!!feedback} onClick={()=>command('answer',a.id)}>{a.label}</button>)}</div>{error?<ErrorNotice message={error}/>:null}</section><aside className="nlhe-feedback panel"><h2>{feedback?'Dein Strategievergleich':'Erst entscheiden, dann vergleichen'}</h2>{feedback?<><p>Gewählt: {question.actions.find(a=>a.id===feedback.chosenAction)?.label}</p>{actions?.map(a=><p className="engine-frequency" key={a.action}><span>{question.actions.find(x=>x.id===a.action)?.label}</span><strong>{number(a.frequency*100)} %</strong></p>)}<p>EV Loss: {feedback.evLoss===null?'EV data unavailable':`${number(Number(feedback.evLoss),3)} BB`}</p><details><summary>Why?</summary><p>Eine mögliche strategische Begründung hängt von Handkategorie, konkreten Suits, Position und SPR ab. Diese Lernstrategie liefert keine Solver-Kausalität.</p><p>Handkategorie: {String((feedback.features as {category:string}).category)}</p><p>{(feedback.features as {flushDraw:boolean}).flushDraw?'Direkter Flush Draw vorhanden. ':''}{(feedback.features as {backdoorFlush:boolean}).backdoorFlush?'Backdoor Flush vorhanden. ':''}</p></details><button className="button button-primary" disabled={busy} onClick={()=>command('next')}>{question.ordinal===session.options.limit?'Training abschließen':'Nächste Entscheidung'}</button></>:<p>Die Frage enthält keine Antwortfrequenzen. Der Server vergleicht deine Action mit der gespeicherten Strategieversion.</p>}<button className="text-button" disabled={busy} onClick={()=>command('finish')}>Sitzung jetzt abschließen</button><ActionLink href={studyUrl(question.spot)} secondary>Exakten Node studieren</ActionLink></aside></div></>;
}
