'use client';
import { useEffect,useMemo,useRef,useState,type CSSProperties } from 'react';
import Link from 'next/link';
import { allHandClasses,getHandClass,createCombo } from '@/domain/cards';
import { seatRoles } from '@/domain/positions';
import type { TournamentState } from '@/domain/tournament-state';
import type { VerifiedSolutionArtifact,ComboAction } from '@/solver/verified-solution';
import type { VerificationResult } from '@/server/verify-solution';
import type { VerifiedQuestion,VerifiedProgress,VerifiedMode,VerifiedSelection } from '@/shared/verified-training';
import { SessionGate } from './auth-screen';
import { api } from './study-context';
import { PageHeader,LoadingPanel,ErrorNotice } from './ui';
import { HoldemCards } from './nlhe-ui';

interface StudyData {artifact:VerifiedSolutionArtifact;verification:VerificationResult;state:TournamentState;progress:VerifiedProgress;question:VerifiedQuestion|null}
const names:Record<string,string>={check:'Check',half:'Bet 2,75 BB',jam:'Jam 13 BB'};
const percent=(n:number)=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:1}).format(n*100)+' %';
const bb=(n:number)=>new Intl.NumberFormat('de-DE',{minimumFractionDigits:2,maximumFractionDigits:3}).format(n)+' BB';

function ActionBars({actions}:{actions:ComboAction[]}){return <div className="verified-bars">{actions.map(a=><div key={a.actionId}><div><strong>{names[a.actionId]}</strong><span>{percent(a.frequency)}</span><span>{a.evBb===undefined?'EV unavailable':`EV ${bb(a.evBb)}`}</span></div><div className="verified-track"><i className={`verified-color-${a.actionId}`} style={{width:`${a.frequency*100}%`}}/></div></div>)}</div>;}
export function VerifiedRiverStudy(){return <SessionGate><RiverContent/></SessionGate>;}
function RiverContent(){
  const [data,setData]=useState<StudyData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [view,setView]=useState<'study'|'train'|'progress'>('study'),[selected,setSelected]=useState('QJs'),[combo,setCombo]=useState('');
  const [filter,setFilter]=useState('all'),[detailed,setDetailed]=useState(false),[mode,setMode]=useState<VerifiedMode>('action'),[selection,setSelection]=useState<VerifiedSelection>('range');
  const grid=useRef<HTMLDivElement>(null),feedbackRef=useRef<HTMLElement>(null),errorRef=useRef<HTMLDivElement>(null);
  async function load(){try{setError('');setData(await api<StudyData>('/api/verified/study'));}catch(e){setError(e instanceof Error?e.message:'Solution konnte nicht geladen werden.');}}
  useEffect(()=>{let active=true;api<StudyData>('/api/verified/study').then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  useEffect(()=>{if(error)errorRef.current?.focus();},[error]);
  const matrix=useMemo(()=>allHandClasses().map(hand=>{
    const rows=data?.artifact.strategies.filter(r=>getHandClass(createCombo(...r.combo))===hand)??[],reach=rows.reduce((s,r)=>s+r.reach,0);
    return {hand,rows,reach,actions:['check','half','jam'].map(actionId=>({actionId,frequency:reach?rows.reduce((s,r)=>s+r.reach*r.actions.find(a=>a.actionId===actionId)!.frequency,0)/reach:0,evBb:reach?rows.reduce((s,r)=>s+r.reach*(r.actions.find(a=>a.actionId===actionId)!.evBb??0),0)/reach:undefined}))};
  }),[data?.artifact]);
  if(!data)return error?<ErrorNotice message={error} retry={()=>void load()}/>:<LoadingPanel label="Solution wird unabhängig geprüft…"/>;
  const hand=matrix.find(h=>h.hand===selected)!,activeRow=hand.rows.find(r=>r.combo.join('')===combo)??hand.rows.find(r=>r.reach>0),q=data.question,report=data.verification.report!;
  function tab(next:typeof view){setView(next);}
  async function send(payload:Record<string,unknown>){
    if(busy)return;setBusy(true);setError('');
    try{const result=await api<{question:VerifiedQuestion;progress:VerifiedProgress;state:TournamentState}>('/api/verified/training',{method:'POST',body:JSON.stringify(payload)});
      setData(current=>current?{...current,...result}:current);setView('train');
      if(result.question.feedback)requestAnimationFrame(()=>feedbackRef.current?.focus());
    }catch(e){setError(e instanceof Error?e.message:'Die Antwort konnte nicht gespeichert werden.');}finally{setBusy(false);}
  }
  function start(){void send({operation:'start',mode,selection});}
  function move(index:number,key:string){const target=key==='ArrowRight'?index+1:key==='ArrowLeft'?index-1:key==='ArrowDown'?index+13:key==='ArrowUp'?index-13:key==='Home'?Math.floor(index/13)*13:key==='End'?Math.floor(index/13)*13+12:-1;if(target<0||target>168)return false;setSelected(matrix[target].hand);setCombo('');grid.current?.querySelectorAll<HTMLButtonElement>('[role="gridcell"]')[target]?.focus();return true;}
  return <div className="verified-study"><PageHeader title="River · verifiziertes Teilspiel" description="8-handed MTT · 15 BB Startstacks · BBA 1 · BTN vs BB"/>
    <div className="verified-scope panel"><strong>VERIFIED_SOLVER · nur dieses River-Teilspiel</strong><p>Das Gleichgewicht gilt für die unten angegebenen Eingangs-Ranges und Check / halben Pot / Jam, danach Fold oder Call. Diese Ranges sind vorgegebene Lernbedingungen. Preflop und frühere Straßen sind nicht als GTO gelöst.</p><Link href="/mtt">MTT-Preflop-Konfiguration →</Link></div>
    <nav className="verified-tabs" aria-label="River-Arbeitsbereich">{([['study','Range studieren'],['train','Am Tisch trainieren'],['progress','Mein Fortschritt']] as const).map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>tab(id)}>{label}</button>)}</nav>
    {error?<div ref={errorRef} tabIndex={-1} role="alert" className="verified-error">{error}</div>:null}
    {view==='study'?<>
      <div className="verified-toolbar"><label>Matrixansicht<select name="matrix-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Alle Actions</option><option value="check">Check</option><option value="half">Raise / Bet</option><option value="jam">Jam</option><option value="mixed">Mixed only</option><option value="reach">Reach</option><option value="ev">EV</option></select></label><label>Prozentwerte<select name="matrix-detail" value={detailed?'detailed':'compact'} onChange={e=>setDetailed(e.target.value==='detailed')}><option value="compact">Compact</option><option value="detailed">Detailed</option></select></label><button className="button-primary" disabled={busy} onClick={start}>Diese Range trainieren</button></div>
      <p>Legende: <span className="verified-legend check">Check</span> <span className="verified-legend half">Bet 2,75 BB</span> <span className="verified-legend jam">Jam 13 BB</span> · Leere Zellen liegen außerhalb der Eingangs-Range. Fold ist am BTN-Check-Node keine Action.</p>
      <div className="verified-range-layout"><section className="panel verified-matrix-panel" aria-label="Gelöste Range"><div className="verified-matrix-scroll" role="region" aria-label="Handmatrix horizontal scrollbar" tabIndex={0}><div ref={grid} role="grid" aria-label="169 Holdem-Handklassen" className={`verified-matrix ${detailed?'detailed':''}`}>{Array.from({length:13},(_,i)=><div role="row" key={i}>{matrix.slice(i*13,i*13+13).map((h,j)=>{const mixed=h.actions.filter(a=>a.frequency>.01).length>1,dim=filter==='mixed'?!mixed:['check','half','jam'].includes(filter)?!h.actions.find(a=>a.actionId===filter)?.frequency:false;return <button role="gridcell" aria-selected={selected===h.hand} tabIndex={selected===h.hand?0:-1} key={h.hand} className={`${h.reach?'supported':'unsupported'} ${dim?'filtered':''}`} aria-label={`${h.hand}: ${h.reach?h.actions.map(a=>`${names[a.actionId]} ${percent(a.frequency)}`).join(', '):'nicht in der Eingangs-Range'}`} onClick={()=>{setSelected(h.hand);setCombo('');}} onKeyDown={e=>{if(move(i*13+j,e.key))e.preventDefault();}}><span className="verified-segments" aria-hidden="true">{h.actions.map(a=><i key={a.actionId} className={`verified-color-${a.actionId}`} style={{width:`${a.frequency*100}%`}}/>)}</span><strong>{h.hand}</strong>{h.reach?<small>{filter==='reach'?percent(h.reach):filter==='ev'?bb(Math.max(...h.actions.map(a=>a.evBb!))):h.actions.filter(a=>a.frequency>.001).map(a=>`${detailed?names[a.actionId]+' ':''}${percent(a.frequency)}`).join(detailed?'\n':' / ')}</small>:<small>—</small>}</button>;})}</div>)}</div></div><p>Prozente sind mit Combo-Reach gewichtet. Board-Blocker bleiben auf Combo-Ebene erhalten.</p></section>
      <aside className="panel verified-detail"><h2>{selected} · Combo-Details</h2>{activeRow?<><div className="verified-combo-buttons">{hand.rows.filter(r=>r.reach>0).map(r=><button key={r.combo.join('')} aria-pressed={activeRow.combo.join('')===r.combo.join('')} onClick={()=>setCombo(r.combo.join(''))}>{r.combo.join(' ')}</button>)}</div><HoldemCards cards={createCombo(...activeRow.combo)}/><p>Reach {percent(activeRow.reach)}</p><ActionBars actions={activeRow.actions}/></>:<p>Für diese Hand gibt es in der festgelegten Eingangs-Range keine Strategie. Sie wird nicht im Trainer gezogen.</p>}<p className="verified-ev-note">EV relativ zu einer gleichmäßigen Aufteilung des 5,5-BB-Ausgangspots; künftige Einsätze und ungerufene Chips sind berücksichtigt. EV Loss vergleicht die verfügbaren Actions derselben Combo.</p></aside></div>
    </>:null}
    {view==='train'?<><div className="verified-toolbar"><label>Trainingsmodus<select name="training-mode" value={mode} disabled={busy} onChange={e=>setMode(e.target.value as VerifiedMode)}><option value="action">Action wählen</option><option value="recall">Frequency Recall</option></select></label><label>Hände auswählen<select name="training-selection" value={selection} onChange={e=>setSelection(e.target.value as VerifiedSelection)}><option value="range">Gesamte gelöste Range</option><option value="smart">Smart Training</option><option value="due">Due for Review</option><option value="weaknesses">My Weaknesses</option><option value="mixed">Mixed Strategy Spots</option></select></label><button className="button-primary" disabled={busy} onClick={start}>{busy?'Wird gespeichert…':q?'Nächste Hand':'Training starten'}</button></div>
      {q?<><PokerTable data={data}/><section className="verified-decision panel" aria-label="Deine Entscheidung"><h2>{q.feedback?'Entscheidung gespeichert':'BTN ist am Zug'}</h2><p>{q.mode==='recall'?'Schätze die Action-Frequenzen dieser konkreten Combo. Zusammen 100 %.':'Wähle deine Action aus dem gelösten Betting Tree.'}</p>{q.mode==='action'?<div className="verified-action-buttons">{data.artifact.actions.map(a=><button className={`verified-action-${a.id}`} key={a.id} disabled={busy||Boolean(q.feedback)} onClick={()=>void send({operation:'answer',id:q.id,action:a.id})}>{names[a.id]}</button>)}</div>:<form key={q.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send({operation:'answer',id:q.id,frequencies:Object.fromEntries(data.artifact.actions.map(a=>[a.id,Number(f.get(a.id))]))});}}><div className="verified-recall">{data.artifact.actions.map(a=><label key={a.id}>{names[a.id]} %<input name={a.id} type="number" inputMode="decimal" min="0" max="100" step="0.1" autoComplete="off" required disabled={busy||Boolean(q.feedback)} defaultValue={a.id==='check'?100:0}/></label>)}</div><button className="button-primary" disabled={busy||Boolean(q.feedback)}>Frequenzen prüfen</button></form>}</section>
      {q.feedback?<section ref={feedbackRef} tabIndex={-1} className="verified-feedback panel" aria-label="Solver-Feedback"><h2>Solver Strategy</h2><p><strong>{q.feedback.category}</strong>{q.action?` · Deine Entscheidung: ${names[q.action]}`:''}</p>{q.feedback.evLossBb!==null?<p className="verified-loss">EV Loss: −{bb(q.feedback.evLossBb)}</p>:<p className="verified-loss">Frequency Accuracy: {percent(q.feedback.score/100)}</p>}<ActionBars actions={q.feedback.actions}/><p>Eine gültige Mixed Action wird nicht als falsch gewertet. Der EV-Vergleich gilt für diese Lösung und ihre festgelegten Eingangs-Ranges.</p><p role="status">Fortschritt gespeichert · {data.progress.decisions} Entscheidungen</p></section>:null}</>:<div className="panel verified-empty"><h2>Dein Platz am River</h2><p>Starte eine Hand aus genau der geprüften Range. Deine Hole Cards erscheinen direkt am BTN-Platz.</p></div>}
    </>:null}
    {view==='progress'?<section className="panel verified-progress"><h2>Mein Lernfortschritt</h2><p>{data.progress.decisions} gespeicherte Entscheidungen · {data.progress.mastery===null?'Mastery noch nicht gemessen':`Mastery ${percent(data.progress.mastery/100)}`} · {data.progress.due} fällige Wiederholungen</p><p>Mastery wird pro physischer Combo und Modus gespeichert: erster Score, danach 65 % bisheriger Wert und 35 % neuer Score. Ab 85 Punkten folgen 1 / 3 / 7 / 14 / 30 Tage; schwächere Antworten kommen nach 10 Minuten wieder.</p>{data.progress.items.length?<div className="verified-progress-scroll"><table><thead><tr><th>Combo</th><th>Modus</th><th>Versuche</th><th>Mastery</th><th>Nächste Wiederholung</th></tr></thead><tbody>{data.progress.items.map(i=><tr key={i.combo+i.mode}><td>{i.combo}</td><td>{i.mode}</td><td>{i.attempts}</td><td>{percent(i.mastery/100)}</td><td>{new Date(i.dueAt).toLocaleString('de-DE')}</td></tr>)}</tbody></table></div>:<p>Noch keine Antworten. Starte die erste Trainingshand.</p>}</section>:null}
    <details className="panel verified-provenance"><summary>Solution, Genauigkeit und genaue Lernbedingungen</summary><p>1 veröffentlichter River-Node · 8 unterstützte Hero-Combos · 56 zulässige Deals · keine MTT-Preflop-Coverage.</p><dl><dt>Solver</dt><dd>{data.artifact.solver.version}</dd><dt>NashConv inklusive numerischer Reserve</dt><dd>≈ {(report.nashConv+report.numericalAllowanceBb).toExponential(2)} BB pro Hand</dd><dt>Prüfung</dt><dd>{report.method} · {report.verifierVersion}</dd><dt>Policy</dt><dd>{data.verification.policyVersion}</dd><dt>Artefakt</dt><dd>{data.artifact.id}</dd><dt>Checksum</dt><dd>{data.artifact.checksum}</dd><dt>Lizenz</dt><dd>{data.artifact.license}</dd></dl><p>Beide Ranges sind gleichgewichtet vor dem Entfernen kollidierender Karten. Sie beschreiben die Startbedingungen dieses Teilspiels und sind keine Preflop-Empfehlung.</p>{data.artifact.context.conditioning!.ranges.map(r=><p key={r.position}><strong>{r.position}:</strong> {r.combos.map(c=>c.cards.join(' ')).join(' · ')}</p>)}<p>BTN hat am River 13 BB, BB 12 BB übrig. Beim Jam wird der ungerufene Überschuss zurückgegeben. Es gibt keine Raises nach einer Bet und keine neu gezogenen Boardkarten.</p></details>
  </div>;
}

function PokerTable({data}:{data:StudyData}){
  const q=data.question!,state=data.state,hero=data.artifact.context.hero,hi=state.seats.findIndex(s=>s.position===hero),positions=state.seats;
  return <section className="verified-table-wrap" aria-label="NLHE Trainingstisch"><div className="verified-poker-table"><div className="verified-felt"><span>River</span><HoldemCards cards={state.board}/><strong>Pot {bb(state.pot/10000)}</strong><small>8-handed · MTT ChipEV · BBA 1</small></div>{positions.map((s,i)=>{const angle=(i-hi)/positions.length*2*Math.PI,roles=seatRoles(positions.length,s.position),last=[...data.artifact.context.actionHistory].reverse().find(e=>e.type!=='DEAL'&&e.actor===s.position),action=s.position===hero&&q.action?names[q.action]:last&&last.type!=='DEAL'?last.type.toLowerCase():'';return <div key={s.position} className={`verified-seat ${s.folded?'folded':''} ${s.position===hero?'hero':''} ${state.actor===s.position?'acting':''}`} style={{left:`${50+41*Math.sin(angle)}%`,top:`${50+39*Math.cos(angle)}%`} as CSSProperties}><span className="verified-seat-position">{s.position}{roles.smallBlind&&s.position==='BTN'?' / SB':''}{roles.button?<i className="verified-dealer" aria-label="Dealer Button">D</i>:null}</span><strong>{bb(s.remaining/10000)}</strong><span className={action.includes('Jam')?'verified-all-in':''}>{action.includes('Jam')?'ALL-IN':action}</span>{s.position===hero?<div className="verified-hole"><small>Deine Hand</small><HoldemCards cards={q.combo} small/></div>:null}</div>;})}</div></section>;
}
