import { describe, expect, it } from 'vitest';
import { assessStrategy } from '../../src/solver/best-response';
import { conditionalActionValues, expectedValue, legalActions, nextHistory, playerToAct, solveKuhn, terminalUtility,
  treeDescription, type StrategyProfile } from '../../src/solver/kuhn';

/** Analytic equilibrium, alpha=1/3. This fixture is not generated by our solver. */
const equilibrium: StrategyProfile = {
  'J:root': [2 / 3, 1 / 3], 'Q:root': [1, 0], 'K:root': [0, 1],
  'J:x': [2 / 3, 1 / 3], 'Q:x': [1, 0], 'K:x': [0, 1],
  'J:b': [1, 0], 'Q:b': [2 / 3, 1 / 3], 'K:b': [0, 1],
  'J:xb': [1, 0], 'Q:xb': [1 / 3, 2 / 3], 'K:xb': [0, 1],
};

describe('Kuhn rules and information sets', () => {
  it('accounts for folds, checks, called bets and net ante contributions', () => {
    expect(terminalUtility(['K', 'J'], 'xx')).toBe(1);
    expect(terminalUtility(['K', 'J'], 'bc')).toBe(2);
    expect(terminalUtility(['J', 'K'], 'xbc')).toBe(-2);
    expect(terminalUtility(['J', 'K'], 'bf')).toBe(1);
    expect(terminalUtility(['K', 'J'], 'xbf')).toBe(-1);
    expect(terminalUtility(['K', 'J'], '')).toBeNull();
    expect(() => terminalUtility(['K', 'J'], 'bb')).toThrow('Invalid history');
  });
  it('builds only legal transitions and identifies the correct player', () => {
    expect(legalActions('')).toEqual(['check', 'bet']);
    expect(legalActions('b')).toEqual(['fold', 'call']);
    expect(playerToAct('xb')).toBe(0);
    expect(playerToAct('x')).toBe(1);
    expect(nextHistory('x', 'bet')).toBe('xb');
    expect(() => nextHistory('', 'call')).toThrow('Illegal action');
    expect(treeDescription().map(node => node.commitments.reduce((sum, value) => sum + value, 0))).toEqual([2, 2, 3, 3]);
  });
  it('weights unknown opponent cards by action reach, instead of exposing the deal', () => {
    // Facing an open bet with Q: J bets 1/3, K bets 1, so posterior is J 1/4, K 3/4.
    // Calling returns +2 or -2: EV = -1, equal to folding. Uniform cards would wrongly give 0.
    expect(conditionalActionValues(equilibrium, 'Q', 'b')).toEqual([-1, -1]);
    const noBet = structuredClone(equilibrium);
    noBet['J:root'] = [1, 0]; noBet['K:root'] = [1, 0];
    expect(() => conditionalActionValues(noBet, 'Q', 'b')).toThrow('Unreachable information set');
  });
});

describe('CFR and independent exhaustive best responses', () => {
  it('recovers known equilibrium value and zero exploitability independently', () => {
    expect(expectedValue(equilibrium)).toBeCloseTo(-1 / 18, 12);
    const exact = assessStrategy(equilibrium);
    expect(exact.bestResponseValues[0]).toBeCloseTo(-1 / 18, 12);
    expect(exact.bestResponseValues[1]).toBeCloseTo(1 / 18, 12);
    expect(exact.exploitability).toBeLessThan(1e-12);
  });
  it('detects a strategically exploitable but normalized uniform policy', () => {
    const uniform = Object.fromEntries(Object.keys(equilibrium).map(key => [key, [0.5, 0.5]])) as StrategyProfile;
    expect(assessStrategy(uniform).exploitability).toBeGreaterThan(0.1);
  });
  it('deterministically converges with full-tree average strategies', () => {
    const profile = solveKuhn(20_000);
    expect(profile).toEqual(solveKuhn(20_000));
    expect(expectedValue(profile)).toBeCloseTo(-1 / 18, 3);
    const exact = assessStrategy(profile);
    expect(exact.exploitability).toBeLessThan(0.005);
    expect(exact.nashConv).toBe(exact.exploitability * 2);
    for (const values of Object.values(profile)) {
      expect(values[0] + values[1]).toBeCloseTo(1, 12);
      expect(values.every(value => value >= 0 && value <= 1)).toBe(true);
    }
  });
  it('rejects invalid solver iteration requests', () => {
    for (const count of [0, -1, 1.1, NaN, Infinity, 10_000_001]) expect(() => solveKuhn(count)).toThrow('Iterations');
  });
});
